/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as ComoInstalarRouteImport } from './routes/como-instalar'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'

const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoInstalarRoute = ComoInstalarRouteImport.update({
  id: '/como-instalar',
  path: '/como-instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/checkout': typeof CheckoutRoute
  '/comercial': typeof ComercialRoute
  '/como-instalar': typeof ComoInstalarRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/checkout': typeof CheckoutRoute
  '/comercial': typeof ComercialRoute
  '/como-instalar': typeof ComoInstalarRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/checkout': typeof CheckoutRoute
  '/comercial': typeof ComercialRoute
  '/como-instalar': typeof ComoInstalarRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/checkout'
    | '/comercial'
    | '/como-instalar'
    | '/inicio'
    | '/login'
    | '/precos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/checkout'
    | '/comercial'
    | '/como-instalar'
    | '/inicio'
    | '/login'
    | '/precos'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/checkout'
    | '/comercial'
    | '/como-instalar'
    | '/inicio'
    | '/login'
    | '/precos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  CheckoutRoute: typeof CheckoutRoute
  ComercialRoute: typeof ComercialRoute
  ComoInstalarRoute: typeof ComoInstalarRoute
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-instalar': {
      id: '/como-instalar'
      path: '/como-instalar'
      fullPath: '/como-instalar'
      preLoaderRoute: typeof ComoInstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  CheckoutRoute: CheckoutRoute,
  ComercialRoute: ComercialRoute,
  ComoInstalarRoute: ComoInstalarRoute,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
